user nginx;
worker_processes 1;

events {
    worker_connections 1024;
}

http {
    include /etc/nginx/mime.types;
    default_type application/octet-stream;

    sendfile on;
    keepalive_timeout 65;

    server {
        listen 80;
        server_name localhost;

        root /usr/share/nginx/html;
        index index.html index.htm;

        # Manejar rutas SPA
        location / {
            try_files $uri $uri/ /index.html;
        }

        # Configuración de headers para CORS si es necesario
        add_header X-Frame-Options DENY;
        add_header X-Content-Type-Options nosniff;
    }
}